version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: viscart_db
    restart: always
    environment:
      POSTGRES_DB: viscart_db
      POSTGRES_USER: viscart_admin
      POSTGRES_PASSWORD: Pm@11@11
    ports:
      - "5432:5432"
    volumes:
      - viscart_postgres_data:/var/lib/postgresql/data

volumes:
  viscart_postgres_data:
