services:
  db:
    image: postgres:16-alpine
    container_name: viscart_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: viscart
      POSTGRES_USER: viscart
      POSTGRES_PASSWORD: viscart_password
    ports:
      - "5432:5432"
    volumes:
      - viscart_postgres_data:/var/lib/postgresql/data

volumes:
  viscart_postgres_data:
